on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]
    paths:
      - "Dockerfile"
      - "pixi.lock"
      - ".github/workflows/docker.yml"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
      - name: Set up environment
        run: |
          git config --global user.name "halfpipe"
          git config --global user.email "halfpipe@fmri.science"
          git config --global datalad.runtime.max-annex-jobs "$(nproc)"
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: mamba-org/setup-micromamba@7f29b8b80078b1b601dfa018b0f7425c587c63bb
        with:
          condarc: |
            channels:
              - conda-forge
          environment-name: datalad
          create-args: >-
            datalad
          cache-environment: true
          init-shell: bash

      - id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: halfpipe/wonkyconn
          tags: |
            type=edge,branch=main
            type=pep440,pattern={{version}}

      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
        id: buildx
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: wonky:conn
          load: true

      - run: |
          datalad get data/halfpipe data/atlases
          docker run --rm \
            --mount="type=bind,source=${{ github.workspace }},target=${{ github.workspace }}" \
            --workdir="${{ github.workspace }}" \
            wonky:conn \
            --phenotypes data/halfpipe/participants.tsv \
            --atlas Schaefer2018Combined data/atlases/atlas-Schaefer2018Combined_dseg.nii.gz \
            data/halfpipe test group

      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        # PRs from forks don't have access to secrets, disable this step in that case.
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        if: github.event_name != 'pull_request'
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: true
